apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: secret-mysql
  namespace: database
spec:
  encryptedData:
    password: AgBoM0gOCWfCFaHkPKtE+MzcOku2cokMLpBVSC/4SXrZlqfuUM7+An7I8xxh82pzFNlUOhexBTI6gLOPDEFn/ieXd/6xmdXQI6QpkVcBDW20ZUO1r+zkCZzQCkBRbCsyeq7YdfW5q9q7fLj0jeONTTIFizR0FoJhEZDBdeIhpK+S2/67KlXpXUO3NM1YkJHYpCu5SDW/6Cr7ZHLvJ5KoUBTY28OPPUl6wt4tKKgxIy4pmLLmgCOGAsK1F3Z6SFpu1V72huLYSOBjBlGfQfBb2vs4nAMPWLWVo6o0GJeuF9zr+3ju9NcasM667QVmgO0VWa64q0QAAfqpKFvcd80dokZHbhZXbaND0tCHlOead9qFqhL92ftqi2AyGRIOWu4n4M0eJdKeIAU8r3FZtyq85YbxkIbWNTb9TCorNNwgIqFtRQ17Dy2A6xpM5paVVQ53xQeWucZhmlyuAgGrCbtmwPXH/aLMeHIVZvRJtFSgsaLcLW/DH3mO2wGLrGg4DNOzNgM0r5z6KFnBYU1+d3koZ4mh/FQp21025ltY6cj64a6AmXf49pl9uxSdIyZsrCntrRByWCNM+kvOKpx2mI4+gIPNtzITa1XJAzw6I5XmBBXDoTT/YkNTYDQ2J75a4GZN9ljfHpGTNLuRxDAyogHGuHE8QMWy4PiHkL7gt/XpEy1ClZj9b/NzuPbOifdgxsg1MsMa0ChvvPtbfuDvN2BJVqmdrktZzpZ5WmsY
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: secret-mysql
      namespace: database

